# Generated by Django 5.1 on 2024-08-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orders_products_ordered_shipping_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_details',
            name='delivery_method',
            field=models.CharField(max_length=100),
        ),
    ]
